fix

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -38,9 +38,13 @@ workflows:
               agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
           - name: Build ipa for distribution
             script: | 
-              xcode-project build-ipa \
-                --workspace "awesomeProject/ios/awesomeProject.xcworkspace" \
-                --scheme "awesomeProject"
+              if [ ! -d "$XCODE_WORKSPACE" ]; then
+            echo "Error: Workspace $XCODE_WORKSPACE does not exist"
+            exit 1
+          fi
+          xcode-project build-ipa \
+            --workspace "$XCODE_WORKSPACE" \
+            --scheme "$XCODE_SCHEME"
         artifacts:
           - build/ios/ipa/*.ipa
           - /tmp/xcodebuild_logs/*.log
